### PR TITLE
Swap `this` for `Dataset<OutQuad, InQuad>` in return of `intersection`

### PR DESCRIPTION
**Pull request by jaxoncreed**
Corrects https://github.com/rdfjs/types/issues/7.

### CODE REVIEW

**Comment by tpluscode** [comment]
@blake-regalia 
We need to merge #4 before we move on to more PRs :)

**Comment by jaxoncreed** [comment]
#4 seems to have been merged. Could this one be merged too?

**Comment by jaxoncreed** [comment]
Hey, just pinging again @blake-regalia @tpluscode

**Review by blake-regalia — APPROVED** [review]

**Comment by blake-regalia** [comment]
pinging @rubensworks for a 2nd approval

**Review by rubensworks — APPROVED** [review]

**Pull request merged**
