### PR TITLE
Added type to export

### PR DESCRIPTION
**Pull request by TessavWalstijn**
Moving from Webpack 4 to Vite 4.

When we build our application we get the error that Vite:
```
✘ [ERROR] Could not resolve "./data-model"

    node_modules/@rdfjs/types/index.d.ts:3:14:
      3 │ export * from './data-model';
        ╵               ~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "./stream"

    node_modules/@rdfjs/types/index.d.ts:4:14:
      4 │ export * from './stream';
        ╵               ~~~~~~~~~~

✘ [ERROR] Could not resolve "./dataset"

    node_modules/@rdfjs/types/index.d.ts:5:14:
      5 │ export * from './dataset';
        ╵               ~~~~~~~~~~~

✘ [ERROR] Could not resolve "./query"

    node_modules/@rdfjs/types/index.d.ts:6:14:
      6 │ export * from './query';
        ╵               ~~~~~~~~~
```

I was able to solve the issue locally by editing the `index.d.ts` from this package.

I hope with this change to make rdfjs accessible for Vite users as well.

### CODE REVIEW

**Comment by tpluscode** [comment]
Hm, having used vite myself, I have not experience such an issue. Could you share your project or a minimal reproduction so that I can understand what's happening here?

**Comment by TessavWalstijn** [comment]
> Hm, having used vite myself, I have not experience such an issue. Could you share your project or a minimal reproduction so that I can understand what's happening here?

Sure I will try to reproduce the issue.

**Comment by tpluscode** [comment]
Oh, I came back here looking at some other PRs and I think I realise that your problem is probably with TS module resolution.

I think a more robust improvement would be to add `.js` extension to imports/exports

**Comment by TessavWalstijn** [comment]
Cool!

Sorry haven't come around it to create a simple way to reproduce my issue.

I might be able to spend some time to try your solution with the next upgrade cycle.

**Comment by tpluscode** [comment]
> Sorry haven't come around it to create a simple way to reproduce my issue.

So, expanding on my comment above, I expect you should be able to reproduce when you set `moduleResolution` to `Node16` or `NodeNext`.

**Comment by TessavWalstijn** [comment]
Hi hi so I was able to create a minimal reproduction:
https://github.com/TessavWalstijn/vue2-ts.rdfjs-types-issue

Switching moduleResolution to:
- `Node10` original
- `Node16`
- `NodeNext`
Did not resolve the issue.

**Comment by rubensworks** [comment]
> That said, export type * was only [introduced in TS5](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#support-for-export-type-). @jeswr @rubensworks would you consider adding this as breaking change and including in v2 of the types? https://github.com/rdfjs/types/pull/46 is already aiming to start a major release...

Sounds good to me!

**Comment by jeswr** [comment]
Sounds good to me too!

**Comment by TessavWalstijn** [comment]
> HI @TessavWalstijn, sorry for dropping the ball on this. I just checked your repro and just changing exports to `export type *` was enough for the errors to go away using the installed TS `v5.1.6`

Yeah no problem I can update the PR.  

I can't remember why I did the `import` then `export`.  

Ping me if there is the need to update the base branch to v2

**Comment by tpluscode** [comment]
> So for some reason I bummed in to this issue: 'Only named exports may use "export type".'

Maybe that was reported by the CI as you can see in the [failed run](https://github.com/rdfjs/types/actions/runs/11930262121/job/33251349328?pr=36)

Please update the dependency to `^5` for typescript

**Comment by tpluscode** [comment]
Uh, why is the CI running `yarn`. Please update your branch once more when #54 is merged

**Review by tpluscode — APPROVED** [review]

**Pull request merged**
